# Setup
title:               Kyeonghwan Gwak
tagline:             '곽경환'
description:         'An undergraduate student at UNIST'
url:                 https://khgwak.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kyeonghwan Gwak
  url:               https://www.linkedin.com/in/kyeonghwan-gwak-7918102b6/
  email:             khgwak@unist.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
